# Generated by Django 4.0.4 on 2022-04-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_book_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('mail', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
